#!/bin/bash

if [ $# -lt 1 ]; then
    echo "You need to enter the directory where the xvectors got extracted to."
    exit 1
fi

xvector_dir=$1

utt2spk=$UTT2SPK
spk2utt=$SPK2UTT

generate_plda() {
    xark=$1

    ### STAGE1: compute scp file to ark generated by the pytorch netowrk
    xfname=$(echo $xark | sed 's/.ark//g')
    mv $xfname.ark $xfname-tmp.ark
    copy-vector ark:$xfname-tmp.ark ark,scp:$xfname.ark,$xfname.scp
    rm $xfname-tmp.ark
    xscp=$xfname.scp

    ### STAGE2: compute the mean vector of all xvectors extracted
    ivector-mean scp:$xscp $xfname-mean.vec
    mean=$xfname-mean.vec

    ### STAGE3: compute the lda transformation matrix
    ivector-compute-lda --total-covariance-factor=0.0 --dim=200 \
        "ark:ivector-subtract-global-mean scp:$xscp ark:- |" \
        ark:$utt2spk $xfname-transform.mat
    trans_mat=$xfname-transform.mat

    ### STAGE4: train the plda
    ivector-compute-plda ark:$spk2utt \
        "ark:ivector-subtract-global-mean scp:$xscp ark:- | transform-vec $trans_mat ark:- ark:- | ivector-normalize-length ark:-  ark:- |" \
        $xfname.plda
    plda=$xfname.plda
}

if [ $# -lt 1 ]; then
    echo "You need to enter the directory where the xvectors can be found"
    exit 1
fi

for I in $(ls $xvector_dir/*_train_*.ark)
do
    generate_plda $I &
done
wait
